const ShopActionTypes = {
  ADD_MEAL_TO_CART: "ADD_MEAL_TO_CART",
  REMOVE_WHOLE_MEAL_FROM_CART: "REMOVE_WHOLE_MEAL_FROM_CART",
  REMOVE_ONE_MEAL_FROM_CART: "REMOVE_ONE_MEAL_FROM_CART",
};

export default ShopActionTypes